
# devops生成文件   开发机 cli 端

app:
  devops_server: "http://0.0.0.0:8083/upfile"        # devops 服务器地址  https:// ...
  server_key: ""           # 上传 devops 服务器秘钥
  key: "mmc"                  # 文件同步 秘钥  (服务器同步数据时需要)


devops:
  full_name: "dollarkillerx/easyutils"        # 名称 例如 dollarkillerx/easyutils
  branch: "master"     # 分支
