# devops生成文件    请填写完成检查确认后 再 运行啊   (每次运行会重写sh模块)


# 这devops系统配置
app:
  host: "0.0.0.0:8083"
  devops_server: "http://0.0.0.0:8083/getfile"        # devops 服务器地址  https:// ...
  server_key: "xxxxxx"                               # 上传 devops 服务器秘钥

# 要自动化部署应用的配置
devops:
  node:
    - port: "8081"                             # 程序运行端口
      full_name: "dollarkillerx/easyutils"     # 名称 例如 dollarkillerx/easyutils
      branch: "master"                         # 分支
      key: "key"                  # 文件同步 秘钥  (服务器同步数据时需要)
      giturl: "https://github"    			   # git pull url 地址 (你要先配置一下秘钥啊!)
      runname: "api"                           # 运行程序的name
      dirpath: "/home/s"                       # 绝对路径
      secondarydirectory: ""                   # 如果有二级目录 就填写在这里
      email: ""                                # 部署成功收邮件通知



