# devops生成文件    请填写完成检查确认后 再 运行啊   (每次运行会重写sh模块)

app:
  host: "0.0.0.0:8083"
  debug: true
  max_request: 1000
  task_num: 10

devops:
  node:
    - port: "8086"      # 程序运行端口
      full_name: "dollarkillerx/easyutils"     # 名称 例如 dollarkillerx/easyutils
      branch: "es"      # 分支
      giturl: "https://github.sads"    # git pull url 地址 (你要先配置一下秘钥啊!)
      runname: "dollarki"   # 运行程序的name
      dirpath: "/asdasd/asdasdasd"   # 绝对路径
      secondarydirectory: ""  # 如果有二级目录 就填写在这里
    - port: "8082"      # 程序运行端口
      full_name: "dollarkillerx/easyutils"     # 名称 例如 dollarkillerx/easyutils
      branch: "us"      # 分支
      giturl: "https://github.sads"    # git pull url 地址 (你要先配置一下秘钥啊!)
      runname: "dollarki"   # 运行程序的name
      dirpath: "/asdasd/asdasdasd/us"   # 绝对路径
      secondarydirectory: "/asdsaadsad"  # 如果有二级目录 就填写在这里  这个是相对路径






